#pragma once

// ConfigInfo = PluginMeta.Config 槽的形状（spec 3.2/D25/D26）。Create/Destroy 是
// **插件镜像内配对**的工厂指针——与 Plugin Create/Destroy 同一理由：跨 DLL 不过 CRT 边界。
// 与 FieldInfo 同格：布局即对外契约，任何布局改动 → kHeaderVersion 递增（D26；§7）。

#include "Vase/Config/FieldInfo.h"

#include <array>
#include <cstddef>
#include <cstdint>
#include <memory>

namespace vase
{

struct ConfigInfo
{
    const FieldInfo* Fields = nullptr;
    std::uint32_t Count = 0;
    std::uint32_t StructSize = 0;
    std::uint32_t StructAlign = 0;
    void* (*CreateConfig)() = nullptr;
    void (*DestroyConfig)(void*) = nullptr;
};

static_assert(std::is_trivially_copyable_v<ConfigInfo>);
// 全零 = 「该插件无配置」：忘写 .Config = FieldsOf<T> 的静默点原样成立（spec 3.4，§13.3 既受）。
static_assert(ConfigInfo{}.Fields == nullptr);

template <typename T>
concept HasVaseConfigFields = requires {
    T::kFields.size();
    T::kFields.data();
    requires std::is_same_v<decltype(T::VaseConfigCreate()), void*>;
    requires std::is_same_v<decltype(T::VaseConfigDestroy(nullptr)), void>;
};

template <typename T>
constexpr ConfigInfo FieldsOf()
{
    static_assert(HasVaseConfigFields<T>, "FieldsOf<T>: T must be generated by VASE_CONFIG");
    return ConfigInfo{
        .Fields = T::kFields.data(),
        .Count = static_cast<std::uint32_t>(T::kFields.size()),
        .StructSize = static_cast<std::uint32_t>(sizeof(T)),
        .StructAlign = static_cast<std::uint32_t>(alignof(T)),
        .CreateConfig = &T::VaseConfigCreate,
        .DestroyConfig = &T::VaseConfigDestroy,
    };
}

} // namespace vase
